### PR TITLE
added userscript

### PR DESCRIPTION
**Pull request by andreasbrett**
To make this more user-friendly I decided to make this a userscript for Tampermonkey. It will automatically load the map below the original map. Had to make 2 slight adjustments to your original JS code and CSS styling to make it work.

### CODE REVIEW

**Comment by cahz** [comment]
Thanks for the contribution!

I don't have much experience with userscripts. Do you maybe have a suggestion to get rid of the code duplication?

**Comment by andreasbrett** [comment]
> Thanks for the contribution!
> 
> I don't have much experience with userscripts. Do you maybe have a suggestion to get rid of the code duplication?

This should work nicely. The view.js is fetched from Github and executed. I needed to load it as text as Github does have CORB protection in place and files can't be sideloaded to websites directly... If you decide to merge this PR to your repo, change the static URL in the userscript as it currently points to view.js from my fork (with those tiny changes to make it integrate in the already rendered Komoot page).

**Comment by cahz** [comment]
Good solution, thank you :+1:

**Comment by WuerfelDev** [comment]
Would be cool to mention the tampermonkey script in the README. I almost created one myself ^^

**Pull request merged**
