### PR TITLE
Rewrite to Maplibre

### PR DESCRIPTION
**Pull request by WuerfelDev**
I wanted to show the map in the komoot style, but leaflet wasn't able to handle the configurations. Switched to maplibre and it's :fire:!
Now we're using komoot's tiles and style file directly.

Todos:

- [X] Style integration
- [X] Zoom to fit regions
- [X] When clicking a region, zoom in!
- [x] Custom layer for background fill (Polygon) and displaying region [name](https://maplibre.org/maplibre-gl-js/docs/examples/variable-offset-label-placement/)
- [x] Fix attribution

### CODE REVIEW

**Comment by WuerfelDev** [comment]
This is a major change but it works really well for me in LibreWolf and Brave.

Changes that aren't the map:
- Position on page is no longer relative
- Show number of available regions below the map

**Comment by cahz** [comment]
This looks really nice, thanks! Just tested in on Chrome and seems to work. 

Just a quick comment: I think the OSM attribution needs to be changed to “OpenStreetMap” with a link to openstreetmap.org/copyright ([Attribution Guidelines](https://osmfoundation.org/wiki/Licence/Attribution_Guidelines)).

I will have a more detailed look into it in a couple of days.

**Comment by WuerfelDev** [comment]
> This looks really nice, thanks! Just tested in on Chrome and seems to work. 
> 
> Just a quick comment: I think the OSM attribution needs to be changed to “OpenStreetMap” with a link to openstreetmap.org/copyright ([Attribution Guidelines](https://osmfoundation.org/wiki/Licence/Attribution_Guidelines)).
> 
> I will have a more detailed look into it in a couple of days.

Oh you're right. The attribution "© OSM" is part of the style specification that Komoot sends and is placed there automatically by maplibre. I don't know if we can override it (but I'll check that). Anyway we could additionally add the correct attribution.

**Comment by WuerfelDev** [comment]
Should be good now

**Comment by cahz** [comment]
Perfect! Thanks

Tested with Firefox and CHrome.

**Comment by LondonRain** [comment]
This is super cool. Thanks!

**Pull request merged**
